"""added foreign key in marketplaces table

Revision ID: b1e11e9d88e7
Revises: daf32e787285
Create Date: 2018-12-20 01:12:08.184559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e11e9d88e7'
down_revision = 'daf32e787285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplaces', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'marketplaces', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketplaces', type_='foreignkey')
    op.drop_column('marketplaces', 'user_id')
    # ### end Alembic commands ###
