"""created a marketplace database

Revision ID: daf32e787285
Revises: 7f846ec742ac
Create Date: 2018-12-19 17:24:22.567948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf32e787285'
down_revision = '7f846ec742ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=64), nullable=False),
    sa.Column('shop_description', sa.Text(), nullable=True),
    sa.Column('shop_logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplaces_shop_name'), 'marketplaces', ['shop_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplaces_shop_name'), table_name='marketplaces')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
