"""added marketplace name to the table

Revision ID: f8e46b3e9836
Revises: fdae78add3e5
Create Date: 2018-12-24 14:46:42.873385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e46b3e9836'
down_revision = 'fdae78add3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplaces', sa.Column('marketplace_name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplaces', 'marketplace_name')
    # ### end Alembic commands ###
