"""added columns for access tokens in the mp table

Revision ID: fdae78add3e5
Revises: daa4dada0351
Create Date: 2018-12-23 01:16:16.680109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdae78add3e5'
down_revision = 'daa4dada0351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketplaces', sa.Column('access_token', sa.String(length=64), nullable=False))
    op.add_column('marketplaces', sa.Column('refresh_token', sa.String(length=64), nullable=True))
    op.drop_index('ix_marketplaces_shop_name', table_name='marketplaces')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_marketplaces_shop_name', 'marketplaces', ['shop_name'], unique=False)
    op.drop_column('marketplaces', 'refresh_token')
    op.drop_column('marketplaces', 'access_token')
    # ### end Alembic commands ###
